release_frame: 1
programs:
  - value: '2Y'
  - value: '1Y'
  - value: 'MMM'
  - value: 'JDMBA'
  - value: 'PT'
  - value: 'EX'
  - value: 'JV'
  - value: 'Faculty/Staff'
section:
  - value: '1Y-Hedgehogs'
  - value: '1Y-Roadrunners'
  - value: 'Big Dogs'
  - value: 'Bucket Heads'
  - value: 'Bull Frogs'
  - value: 'Cash Cows'
  - value: 'Highlanders'
  - value: 'Moose'
  - value: 'Poets'
  - value: 'Turkeys'
  - value: 'N/A'
kwesttrip:
  - value: 'N/A'
  - value: 'Adriatic Riviera-2015'
  - value: 'Alps: Switzerland-2015'
  - value: 'Amalfi Coast-2015'
  - value: 'Amazing race-2014'
  - value: 'Amazing Race-2015'
  - value: 'Argentina-2014'
  - value: 'Aruba-2015'
  - value: 'Arubacao-2014'
  - value: 'Bavaria-2015'
  - value: 'Belize-2014'
  - value: 'Belize-2015'
  - value: 'Berlin/Krakow-2014'
  - value: 'Bike France-2015'
  - value: 'Bike Holland-2014'
  - value: 'Brazil-2015'
  - value: 'British Isles-2015'
  - value: 'Cataluna-2015'
  - value: 'Chile-2014'
  - value: 'Chile-2015'
  - value: 'Costa Rica-2014'
  - value: 'Costa Rica-2015'
  - value: 'Croatia-2014'
  - value: 'Croatia-2015'
  - value: 'Czechoslovakia-2014'
  - value: 'Denmark/Austria-2014'
  - value: 'Ecuador/Galapagos-2015'
  - value: 'Ecuador-2014'
  - value: 'Family-2014'
  - value: 'Finland/Estonia-2015'
  - value: 'Georgia/Armenia-2014'
  - value: 'Greece-2014'
  - value: 'Greece-2015'
  - value: 'Guatemala-2014'
  - value: 'Guatemala-2015'
  - value: 'Hong Kong/Macau-2015'
  - value: 'Hungary-2014'
  - value: 'Iceland-2014'
  - value: 'Iceland-2015'
  - value: 'Ireland-2014'
  - value: 'Italy-2014'
  - value: 'Jordan-2015'
  - value: 'Korea-2015'
  - value: 'Montenegro-2015'
  - value: 'Morocco-2015'
  - value: 'Mystery-2014'
  - value: 'Mystery-2015'
  - value: 'Netherlands-2015'
  - value: 'Nicaragua-2014'
  - value: 'Nicaragua-2015'
  - value: 'Northern Spain-2014'
  - value: 'Northern Spain-2015'
  - value: 'Norway/Sweden-2015'
  - value: 'Oman-2014'
  - value: 'Panama-2014'
  - value: 'Peru-2014'
  - value: 'Portugal-2014'
  - value: 'Portugal-2015'
  - value: 'Puerto Rico-2014'
  - value: 'Romania-2014'
  - value: 'Romania-2015'
  - value: 'Spain Mediterranean-2014'
  - value: 'St. Lucia/Barbados-2015'
  - value: 'St. Lucia-2014'
  - value: 'Sweden-2014'
  - value: 'Thailand-2014'
  - value: 'Thailand-2015'
  - value: 'Top Chef (Peru)-2015'
  - value: 'Turkey-2014'
  - value: 'Turkey-2015'
  - value: 'Uruguay/Argentina-2015'
  - value: 'Vietnam-2014'
  - value: 'Vietnam-2015'
countries:
  - value: "United States"
  - value: "Afghanistan"
  - value: "Albania"
  - value: "Algeria"
  - value: "Andorra"
  - value: "Angola"
  - value: "Antigua and Barbuda"
  - value: "Argentina"
  - value: "Armenia"
  - value: "Australia"
  - value: "Austria"
  - value: "Azerbaijan"
  - value: "Bahamas"
  - value: "Bahrain"
  - value: "Bangladesh"
  - value: "Barbados"
  - value: "Belarus"
  - value: "Belgium"
  - value: "Belize"
  - value: "Benin"
  - value: "Bhutan"
  - value: "Bolivia"
  - value: "Bosnia and Herzegovina"
  - value: "Botswana"
  - value: "Brazil"
  - value: "Brunei Darussalam"
  - value: "Bulgaria"
  - value: "Burkina Faso"
  - value: "Burundi"
  - value: "Cabo Verde"
  - value: "Cambodia"
  - value: "Cameroon"
  - value: "Canada"
  - value: "Central African Republic"
  - value: "Chad"
  - value: "Chile"
  - value: "China"
  - value: "Colombia"
  - value: "Comoros"
  - value: "Congo"
  - value: "Costa Rica"
  - value: "Côte d'Ivoire"
  - value: "Croatia"
  - value: "Cuba"
  - value: "Cyprus"
  - value: "Czech Republic"
  - value: "Democratic People's Republic of Korea (North Korea)"
  - value: "Democratic Republic of the Cong"
  - value: "Denmark"
  - value: "Djibouti"
  - value: "Dominica"
  - value: "Dominican Republic"
  - value: "Ecuador"
  - value: "Egypt"
  - value: "El Salvador"
  - value: "Equatorial Guinea"
  - value: "Eritrea"
  - value: "Estonia"
  - value: "Ethiopia"
  - value: "Fiji"
  - value: "Finland"
  - value: "France"
  - value: "Gabon"
  - value: "Gambia"
  - value: "Georgia"
  - value: "Germany"
  - value: "Ghana"
  - value: "Greece"
  - value: "Grenada"
  - value: "Guatemala"
  - value: "Guinea"
  - value: "Guinea-Bissau"
  - value: "Guyana"
  - value: "Haiti"
  - value: "Honduras"
  - value: "Hungary"
  - value: "Iceland"
  - value: "India"
  - value: "Indonesia"
  - value: "Iran"
  - value: "Iraq"
  - value: "Ireland"
  - value: "Israel"
  - value: "Italy"
  - value: "Jamaica"
  - value: "Japan"
  - value: "Jordan"
  - value: "Kazakhstan"
  - value: "Kenya"
  - value: "Kiribati"
  - value: "Kuwait"
  - value: "Kyrgyzstan"
  - value: "Lao People's Democratic Republic (Laos)"
  - value: "Latvia"
  - value: "Lebanon"
  - value: "Lesotho"
  - value: "Liberia"
  - value: "Libya"
  - value: "Liechtenstein"
  - value: "Lithuania"
  - value: "Luxembourg"
  - value: "Macedonia"
  - value: "Madagascar"
  - value: "Malawi"
  - value: "Malaysia"
  - value: "Maldives"
  - value: "Mali"
  - value: "Malta"
  - value: "Marshall Islands"
  - value: "Mauritania"
  - value: "Mauritius"
  - value: "Mexico"
  - value: "Micronesia (Federated States of)"
  - value: "Monaco"
  - value: "Mongolia"
  - value: "Montenegro"
  - value: "Morocco"
  - value: "Mozambique"
  - value: "Myanmar"
  - value: "Namibia"
  - value: "Nauru"
  - value: "Nepal"
  - value: "Netherlands"
  - value: "New Zealand"
  - value: "Nicaragua"
  - value: "Niger"
  - value: "Nigeria"
  - value: "Norway"
  - value: "Oman"
  - value: "Pakistan"
  - value: "Palau"
  - value: "Panama"
  - value: "Papua New Guinea"
  - value: "Paraguay"
  - value: "Peru"
  - value: "Philippines"
  - value: "Poland"
  - value: "Portugal"
  - value: "Qatar"
  - value: "Republic of Korea (South Korea)"
  - value: "Republic of Moldova"
  - value: "Romania"
  - value: "Russian Federation"
  - value: "Rwanda"
  - value: "Saint Kitts and Nevis"
  - value: "Saint Lucia"
  - value: "Saint Vincent and the Grenadines"
  - value: "Samoa"
  - value: "San Marino"
  - value: "Sao Tome and Principe"
  - value: "Saudi Arabia"
  - value: "Senegal"
  - value: "Serbia"
  - value: "Seychelles"
  - value: "Sierra Leone"
  - value: "Singapore"
  - value: "Slovakia"
  - value: "Slovenia"
  - value: "Solomon Islands"
  - value: "Somalia"
  - value: "South Africa"
  - value: "South Sudan"
  - value: "Spain"
  - value: "Sri Lanka"
  - value: "Sudan"
  - value: "Suriname"
  - value: "Swaziland"
  - value: "Sweden"
  - value: "Switzerland"
  - value: "Syrian Arab Republic"
  - value: "Tajikistan"
  - value: "Thailand"
  - value: "Timor-Leste"
  - value: "Togo"
  - value: "Tonga"
  - value: "Trinidad and Tobago"
  - value: "Tunisia"
  - value: "Turkey"
  - value: "Turkmenistan"
  - value: "Tuvalu"
  - value: "Uganda"
  - value: "Ukraine"
  - value: "United Arab Emirates"
  - value: "United Kingdom of Great Britain and Northern Ireland"
  - value: "United Republic of Tanzania"
  - value: "Uruguay"
  - value: "Uzbekistan"
  - value: "Vanuatu"
  - value: "Venezuela"
  - value: "Vietnam"
  - value: "Yemen"
  - value: "Zambia"
  - value: "Zimbabwe"